### ISSUE TITLE
digits-sklearn-opencv doesn't work anymore

### ISSUE THREAD

**Issue by remram44** [ViDA-NYU/reprozip-examples#13]
```
Traceback (most recent call last):
  File "generateClassifier.py", line 10, in <module>
    dataset = datasets.fetch_mldata("MNIST Original")
  File "/home/vagrant/.virtualenvs/digits-sklearn-opencv/local/lib/python2.7/site-packages/sklearn/datasets/mldata.py", line 142, in fetch_mldata
    mldata_url = urlopen(urlname)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 651, in http_error_302
    fp.read()
  File "/usr/lib/python2.7/socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "/usr/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
socket.error: [Errno 104] Connection reset by peer
```

Did they move or rename the dataset?

**Comment by remram44** [comment]
Interestingly curl has no issue downloading `http://mldata.org/repository/data/download/matlab/mnist-original` but the urlopen() call fails (but --verbose shows a warning).

**Comment by remram44** [comment]
Getting `500 Internal Server Error` today.

**Comment by remram44** [comment]
Link works again today

**Comment by remram44** [comment]
The [file is on OSF](https://osf.io/jda6s/) (since 42cfbd8a), so this is more a rotten dep than a bug.

The file seems to get generated on the fly, it has an embedded timestamps. I don't see any change in the file other than the timestamp.
