### ISSUE TITLE
stacked-up example is not working after install

### ISSUE THREAD

**Issue by fchirigati** [ViDA-NYU/reprozip-examples#16]
When running the `runserver` script:

     * Starting PostgreSQL 9.5 database server
    Traceback (most recent call last):
      File "./manage.py", line 7, in <module>
        from django.core.management import execute_from_command_line
    ImportError: No module named django.core.management
     * Stopping PostgreSQL 9.5 database server

This is caused by an error while installing the dependencies from stacked-up:

    ==> default: Collecting six==1.2.0 (from -r requirements.txt (line 12))
    ==> default:   Downloading six-1.2.0.tar.gz
    ==> default:     Complete output from command python setup.py egg_info:
    ==> default:     Traceback (most recent call last):
    ==> default:       File "<string>", line 1, in <module>
    ==> default:       File "/home/vagrant/.virtualenvs/stacked-up/local/lib/python2.7/site-packages/setuptools/__init__.py", line 160, in <module>
    ==> default:         monkey.patch_all()
    ==> default:       File "/home/vagrant/.virtualenvs/stacked-up/local/lib/python2.7/site-packages/setuptools/monkey.py", line 90, in patch_all
    ==> default:         patch_for_msvc_specialized_compiler()
    ==> default:       File "/home/vagrant/.virtualenvs/stacked-up/local/lib/python2.7/site-packages/setuptools/monkey.py", line 142, in patch_for_msvc_specialized_compiler
    ==> default:         msvc = import_module('setuptools.msvc')
    ==> default:       File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    ==> default:         __import__(name)
    ==> default:       File "/home/vagrant/.virtualenvs/stacked-up/local/lib/python2.7/site-packages/setuptools/msvc.py", line 25, in <module>
    ==> default:         from six.moves import filterfalse
    ==> default:     ImportError: cannot import name filterfalse

**Comment by remram44** [comment]
This is why we have the Box and ReproZip :wink: Dependencies break.

It looks like setuptools updates six while it depends on it, and crashes?

**Comment by remram44** [comment]
So stacked-up depends on `six==1.2.0` (in requirements.txt) while setuptools & pip use six 1.10. pip downgrades six as requested then becomes broken. Changing the requirement to `six>=1.2.0` might be enough (then we rely on six's backwards compatibility...)

**Comment by remram44** [comment]
This seems to work in the pre-built VM on OSF, so I'll mark this as "rotten".
